### ISSUE TITLE
Composer install require error

### ISSUE THREAD

**Issue by alexmanase** [jeffreyvr/tailpress-installer#5]
Hi there! I tried to install the tailpress-installer and I've got the following error.

![image](https://user-images.githubusercontent.com/10696975/200543912-b59a4571-e174-4787-86bf-b3736b93d2cc.png)

**Comment by jeffreyvr** [comment]
PHP 8.1 is not yet supported for the installer. Will try to update this later today, or if you are able to create a PR - feel free to do so :)

**Comment by alexmanase** [comment]
I'll try to fix it.

**Comment by alexmanase** [comment]
Hi @jeffreyvr ! I tried to find the package `phpstan/phpstan-shim` to replace it (https://github.com/phpstan/phpstan-shim), but I couldn't find it :(. Do you have any idea how to fix it?

**Comment by jeffreyvr** [comment]
I've updated the package to support PHP 8.1, can you try again?

Make sure to update the installer to the latest version. 

```
composer global require jeffreyvanrossum/tailpress-installer:1.0.1
```

**Comment by alexmanase** [comment]
I tried and it failed. Although, I was able to install it using `--ignore-platform-reqs`, I don't think it's the ideal way.

```
composer global require jeffreyvanrossum/tailpress-installer --ignore-platform-reqs
```

![image](https://user-images.githubusercontent.com/10696975/201062470-125df0ae-0d55-498f-9d04-773a5c804d2f.png)

**Comment by jeffreyvr** [comment]
Not sure why this is. The installer does not require phpstan. To be sure, you don't have phpstan as a global package installed?

**Comment by alexmanase** [comment]
That's it. For some reason I had `phpstan/phpstan-shim` installed as a global package.

Thank you!
