### ISSUE TITLE
Support Vite

### ISSUE THREAD

**Issue by prpanto** [jeffreyvr/tailpress-installer#7]
Can you support Vite instead mix. The mix doesn't support any more Laravel use vite anyway and it's better and faster.

**Comment by jeffreyvr** [comment]
I would be open to a PR that adds support for Vite as an option (like esbuild is an option now as well). I looked into adding it when Laravel made it the default, but I didn't find it all that easy to setup in the context of WordPress back then. Maybe it's different now.

I won't drop support for Mix anytime soon though. I think Mix is stable, not slow (though that might depend on the project) and has a expressive API to change the configuration.
